questionsList = [
  'Who are you?',
  'How would you describe yourself?',
  'What are you passionate about?',
  'What personal achievements are you most proud of?',
  'What are you most grateful for?',
  'What are the most important things to you in life?',
  'What are your values?',
  ' What do you represent?',
  ' What do you want to embody?',
  'Do you love yourself?',
  'Why or why not?',
  ' What do you love most about yourself?',
  'How can you love yourself more today?',
  'What is your ideal self?',
  'Look at your life now. Are you living the life of your dreams?',
  ' Why or why not?',
  'If you have one year left to live, what would you do?',
  'If you have one week left to live, what would you do?',
  'If you have one day left to live, what would you do?',
  'If you have one minute left to live, what would you do?',
  'What would you do today if there were no tomorrow?',
  'What are the biggest things you’ve learned in life to date?',
  'What advice would you give to your younger self?',
  'Let’s say you are your future self. What advice would you give to your present self?',
  'Is there something you’re still holding on to?',
  ' Is it time to let it go?',
  'What are you busy with today?',
  ' Will this matter in 1 year?',
  ' 3 years?',
  ' 5 years?',
  'What are your Quadrant 2 tasks?',
  ' How can you start working on them?',
  'What opportunities are you looking for now?',
  'How can you create these opportunities?',
  'What are your biggest goals and dreams?',
  'Is there anything stopping you from pursuing them?',
  ' Why?',
  ' How can you address these factors?',
  'If you were to do something for free for the rest of your life, what would you want to do?',
  'What would you do if you cannot fail; if there were no limitations in money, resources, time, or networks?',
  'What do you want to achieve in 1 year?',
  'What do you want to achieve in 3 years?',
  'What do you want to achieve in 5 years?',
  'What do you want to achieve in 10 years?',
  'How important are these goals to you?',
  'What if these goals are doubled?',
  ' Tripled?',
  ' Magnified by 10?',
  ' How would you feel?',
  ' Would you prefer to achieve these or your previous goals?',
  'Who are the people who have achieved similar goals?',
  ' What can you learn from them?',
  'Are you putting any parts of your life on hold?',
  ' Why?',
  'What’s the top priority in your life right now?',
  ' What are you doing about it?',
  'If you were to die tomorrow, what would be your biggest regret?',
  ' What can you do now to make sure that it doesn’t happen?',
  'Looking back on your life, have you made any mistakes before?',
  ' What happened, and why?',
  'What have you learned from those episodes?',
  'What is your biggest frustration right now?',
  ' What can you do about it?',
  'What is the biggest thing you can do now, that will change your life for the better?',
  '…How can you start working on that?',
  'If you had a million dollars, what would you do with it?',
  'Do you love your job?',
  ' Why or why not?',
  'What is your ideal career?',
  'How can you start to create your ideal career starting today?',
  'What is your ideal diet?',
  'What do you need to do to achieve your ideal diet?',
  'What is your ideal home like?',
  'What do you need to do to achieve your ideal home?',
  'What is your ideal physical look?',
  'What do you need to do to achieve your ideal physical look?',
  'What is your ideal life?',
  'What can you do to start living your ideal life?',
  'What would you want to say to yourself in 1 year’s time?',
  'Who do you think you will be in 3 years?',
  'Who do you think you will be in 5 years?',
  'Who do you think you will be in 10 years?',
  'What do you fear most in life?',
  ' Why?',
  'Is there anything you are running away from?',
  'Are you settling for less than what you are worth?',
  ' Why?',
  'What is your inner dialogue like?',
  'What limiting beliefs are you holding on to?',
  'Are they helping you achieve your goals?',
  'If not, is it time to let them go?',
  'What empowering beliefs can you take on to help you achieve your goals?',
  'What bad habits do you want to break?',
  'What good habits do you want to cultivate?',
  'What are the biggest actions you can take now to create the biggest results in your life?',
  'Where are you living right now — in the past, future, or present?',
  'Are you living your life to the fullest right now?',
  'What is the meaning of life?',
  'What is your life purpose?',
  ' Why do you exist?',
  ' What is your mission?',
  'How can you make your life more meaningful, starting today?',
  'What drives you?',
  'What are the times you are most inspired, most motivated, most charged up?',
  'What did you do during those times?',
  ' How can you do more of that starting today?',
  'How can you change someone’s life for the better today?',
  'Who are the 5 people you spend the most time with?',
  'Are these people enabling you or holding you back?',
  'What qualities do you want to embody?',
  ' (Refer to Q7: Values and Q11: Ideal Self) Where can you meet people who embody these qualities?',
  'Who inspire you the most?',
  'How can you be like them?',
  'What is your ideal life partner like?',
  'Where can you find him/her?',
  'How can you get to know him/her?',
  'Are you afraid of letting others get close to you and why?',
  'Who is/are the most important person(s) to you in the world?',
  'Are you giving them the attention you want to give?',
  'How can you spend more time with them starting today?',
  'What kind of person do you enjoy spending time with?',
  'How can you be this person to others?',
  'Who do you want to be like in 1 year?',
  'Who do you want to be like in 3 years?',
  'Who do you want to be like in 5 years?',
  'Who do you want to be like in 10 years?',
  'Who are your mentors in life?',
  'What is one thing you’re going to do differently after reading this article?',
  'Are you doing what you truly want to do?',
  'Do you have a dream to follow?',
  'Are you proud of what you’re doing or what you’ve done?',
  'How many promises have you made and how many of them have you fulfilled?',
  'What’s the one thing you really want to do but have never done so, and why?',
  'Have you ever failed anyone who you loved or loved you?',
  'Will you take a shot if the chance of failure and success is 50-50?',
  'If you could travel to the past in a time machine, what advice would you give to the 6-year-old you?',
  'Will you break the rules because of something/someone you care about?',
  'Have you ever abandoned a creative idea that you believed because others thought you were a fool?',
  'What would you prefer?',
  ' Stable but boring works or interesting works with lots of workload?',
  'Are you afraid of making mistakes even though there’s no punishments at all?',
  'If you would clone yourself, which of your characteristics you wouldn’t want to be cloned?',
  'What’s the difference between you and most of the other people?',
  'Are you making some influences on the world or constantly being influenced by the world?',
  'The thing you cried for last time, does it matter to you now or will it matter to you 5 years later?',
  'Is there anything you can’t let go of but you know you should?',
  'Do you remember anyone you hated 10 years ago?',
  ' Does it matter now?',
  'Which makes you happier, to forgive someone or to hate someone forever?',
  'What are you worrying about and what’s the difference if you stop worrying about it?',
  'If you’d die now, would you have any regrets?',
  'Which one would you prefer, having a luxurious trip alone or having a picnic with people you love?',
  'Who do you admire and why?',
  'Is there anyone who inspired you and made you who you are today?',
  'What’s the thing you’re most satisfied with?',
  'When was the last time you laughed and what did you laugh at?',
  'Are you doing anything which makes you and people around you happy?',
  'Is there anyone who you love or loves you?',
  'When was the last time you really talked with your parents/family?',
  'If happiness is a currency, how rich do you think you are?',
  'If today’d be the end of the world, what’d you do?',
  'Is there something that you’ve dreamt of doing for a long time?',
  ' Why haven’t you done it?',
  'What would you like to change about your family?',
  'What was a place or event that transformed your ideas, thinking, perspective, or made you come alive in a new way?',
  ' What changed?',
  'What one thing you would do if it would be impossible to fail?',
  'What is something you love now, that you never could have imagined you would like in the past?',
  'If you could invite anyone, living or dead to dinner, who would that be and why?',
  'If a crystal ball could tell you the truth about yourself, your life, the future or anything else, what would you want to know?',
  'What are you addicted to?',
  'What’s the milestone you’re working towards right now in your personal and professional life?',
  'What was the most bizarre encounter you’ve had in your life?',
  'What are you most likely very wrong about?',
  'What chapters would you separate your autobiography into?',
  'What are some things you’ve had to unlearn?',
  'What could you give a 40-minute presentation on with absolutely no preparation?',
  'What question would you most like to know the answer to?',
  'If you didn’t have to sleep, what would you do with the extra time?',
  'Why did you decide to do what you are doing now in your life?',
  'What’s the best and worst piece of advice you’ve ever received?',
  'What’s the most impactful ‘no’ you’ve said recently?',
  'What was the most stressful experience of your life?',
  'If you were to die this evening with no opportunity to communicate with anyone, what would you most regret not having told someone?',
  ' Why haven’t you told them yet?',
  'What do you spend too much time doing?',
  ' What don’t you spend enough time doing?',
  'What makes you feel most alive?',
  'What is something you know you do differently than most people?',
  'What advice would you offer to yourself five years ago?',
  ' One year ago?',
  'What small gesture from a stranger made a big impact on you?',
  'What are you looking forward to in the coming months?',
  'Did you ever feel lost in your life path?',
  ' How did you find your way again?',
  'What do you want your epitaph to be?',
  'What do you regret not doing?',
  ' Why haven’t you done it?',
  'What would constitute a perfect day for you?',
  'What’s something you love about yourself?',
  'When do you feel truly alive?',
  'When people come to you for help, what do they usually want help with?',
  'What do you consider as your biggest achievement in the last 5 years?',
  'What is the most challenging part of your job?',
  ' How do you handle it?',
  'What was a major turning point in your life?',
  'What’s one thing that could happen today that would make it great?',
  'If you knew that in one year you would die suddenly, would you change anything about the way you are now living?',
  ' Why?',
  'What would you like to ask yourself?'
]
